version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gps_tracker
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.29
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    restart: unless-stopped

volumes:
  mongodb_data: 